### ISSUE TITLE
Update cordova-ios CocoaPod version

### ISSUE THREAD

**Issue by Ajaxy** [phonegap/phonegap-webview-ios#10]
Hello! Thank you for all awesome.

I figured out (regarding to #6) that you are able to push new versions to https://cocoapods.org/pods/Cordova
I really need it because of [this commit](https://github.com/apache/cordova-ios/commit/813a3bac10320c70a890aaf35ea96a069c6b8e21) that was added in 4.1.0. It allows to overwrite the default path to `config.xml`. I will be really grateful if you push the updated .podspec file.

Thank you!

**Comment by revolunet** [comment]
did you try the git: syntax ? 

example :

``` ruby
pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :commit => '082f8319af'
```

https://guides.cocoapods.org/using/the-podfile.html`

**Comment by Ajaxy** [comment]
I can't use it as I create my own pod and specify dependencies in .podspec file.

**Comment by hollyschinsky** [comment]
Hi @Ajaxy! 

Sure, I will update the .podspec file and push it this week. I'll post here again once it's available. 

~Holly

**Comment by hollyschinsky** [comment]
Hi @Ajaxy! 

I've [updated the .podspec to 4.1.1](https://cocoapods.org/?q=cordova), tested with the version of all the plugins included in this project and submitted it to the CocoaPods repo. 

Please let me know if it's working for you now.

Thanks! 
Holly

**Comment by Ajaxy** [comment]
Hi @hollyschinsky!

Thank you much, it's working now!

**Comment by hollyschinsky** [comment]
@Ajaxy Excellent!
