### ISSUE TITLE
Update cordova-ios CocoaPod version to 4.2.1

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-webview-ios#14]
Current version uses 4.1.1 (https://github.com/phonegap/phonegap-webview-ios/issues/10)

Can you update the pod to use 4.2.1? https://cordova.apache.org/announcements/2016/08/22/android-ios-release.html

**Comment by hollyschinsky** [comment]
@jcesarmobile Yes, I will work on getting that updated this week.

**Comment by hollyschinsky** [comment]
I pushed this update to 4.2.1 today, closing...
