### ISSUE TITLE
Update cordova-ios CocoaPod version to latest

### ISSUE THREAD

**Issue by pchariskos** [phonegap/phonegap-webview-ios#21]
Hello!

My app is crashing because of the issue CB-12341 which was solved in apache/cordova-ios a couple of months ago. I would be pleased if you can push the new version to [https://cocoapods.org/pods/Cordova]()

Thanks!

**Comment by hollyschinsky** [comment]
@pchariskos I see that issue was resolved in cordova-ios 4.4.0 and the latest released version is 4.3.1. A new version with that fix included is set to be released any day now though so I will update it as soon as it's released. 

Thanks!
Holly

**Comment by yaroslav-v** [comment]
Hi!

Thanks for very useful repository! [Cordova iOS 4.4.0](https://cordova.apache.org/announcements/2017/04/26/ios-release.html) is released now :). Could you update pods, please?

**Comment by yaroslav-v** [comment]
@hollyschinsky Hi! Do you have any plans regarding pods update? :)

**Comment by hollyschinsky** [comment]
Hi @yaroslav-v Yes I should be able to do this by end of week. Cheers, Holly

**Comment by yaroslav-v** [comment]
Thanks!

**Comment by hollyschinsky** [comment]
@yaroslav-v I've updated it but still waiting for it to push to the Cocoapods repo. It looks like it might be down at the moment but I'll keep checking and let you know when it's there. Thx! Holly

**Comment by hollyschinsky** [comment]
@yaroslav-v pchariskos Cordova iOS v4.4.0 has been pushed to the cocoapods registry. Cheers, Holly
