### ISSUE TITLE
Update Cocoapods version

### ISSUE THREAD

**Issue by EddyVerbruggen** [phonegap/phonegap-webview-ios#6]
Hi,

Thanks for this tutorial (and a few other repo's and blogs Holly wrote), it helped me enormously embedding a Cordova webview to an existing native app!

Sorry to post this question on this repo but I don't know of a better place to ask.

On Cocoapods the latest podspec is for [version 3.9.1](https://github.com/CocoaPods/Specs/tree/master/Specs/Cordova), but I'd love to use cordova-ios-4.x, so I wondered: who is pushing those podspecs out to Cocoapods and is there a plan to push 4.x as well?

Otherwise I'll host it as a private pod, no harm done, but I rather not.

Cheers,
Eddy

**Comment by hollyschinsky** [comment]
Hi Eddy! 

Yes, this is a valid point. When I originally worked on this cordova-ios-4.x was not available. But now that it is and with the features it offers, we really need to get this updated. 

I will get on it and post updates on status here. Glad to hear you're using it and please continue to provide any new feedback! 

Also, just FYI, I added info to the PhoneGap Docs on how to use this with Swift  [here](http://docs.phonegap.com/develop/1-embed-webview/ios/#swift) in case you're interested in checking that out.

Cheers!
Holly

**Comment by EddyVerbruggen** [comment]
Yes I saw your Swift video as well - your timing is just perfect for me :)

Thanks in advance for your efforts on updating the podspec!

**Comment by hollyschinsky** [comment]
Hi Eddy, Awesome! I hope to see you at PhoneGap Day EU and hear about all the latest cool stuff you're working on :) 

I wanted to post a status update on this.  I've created and tested a [new CocoaPod spec for Cordova iOS 4.0.1](https://github.com/phonegap/phonegap-webview-ios/blob/master/core-podspecs/Cordova.podspec) and also updated all of the [plugin podspecs](https://github.com/phonegap/phonegap-webview-ios/tree/master/core-podspecs) while I was at it. They all now depend on this latest Cordova version and the latest plugin branch for each. 

Since we were not the original authors of the `Cordova.podspec`, however, I can't publish it yet. I think I found the person (Ernesto Rivera) and emailed him to see if he could add me on as a contributor. Until then I can't push any of the updates but hopefully I will hear back soon. I will update this as soon as I do.

Cheers!
Holly

**Comment by EddyVerbruggen** [comment]
Hey Holly, thank you so much for doing this (I guess) tedious update!

I hope you'll hear back from him soon.

And I'm sure looking forward chatting with you at PGDay EU, I'll bore you to death with the app I'm using this for ;)

**Comment by hollyschinsky** [comment]
Hi Eddy! 

Good news, I was able to get access to the repo for the Cordova spec and pushed a new update for 4.0.1 today. Now that I am listed as an owner I can push updates in the future as well which is nice. I also pushed all of the new plugin specs that point to this latest version for the Cordova dependency and set them to the latest tag of the plugin available. Lastly, I updated and pushed a new version of this project to the CocoaPods repo which includes all of these new plugins and dependencies in the sample template project so it will use the latest. I tested it out with Obj-C and Swift directly from the repo tonight and it's all working for me well. Please file an issue if you find any problems.

Also, you probably already know this but if you're using these pods in a project you already had defined them in you'll need to run a `$ pod update` to get all the latest. Here's what you should see showing the latest versions of everything. 

```
hschinsk-osx:c5 hschinsk$ pod update
Downloading dependencies
Using Cordova (4.0.1)
Using CordovaPlugin-console (0.2.10)
Using cordova-plugin-camera (2.1.0)
Using cordova-plugin-contacts (2.0.1)
Using cordova-plugin-device (1.1.1)
Using cordova-plugin-device-motion (1.2.0)
Using cordova-plugin-device-orientation (1.0.2)
Using cordova-plugin-file (4.1.1)
Installing cordova-plugin-file-transfer 1.5.0 (was 1.3.0)
Using cordova-plugin-geolocation (2.1.0)
Using cordova-plugin-globalization (1.0.2)
Using cordova-plugin-inappbrowser (1.3.0)
Installing cordova-plugin-media-capture 1.2.0 (was 1.0.1)
Using cordova-plugin-network-information (1.2.0)
Using cordova-plugin-splashscreen (2.1.0)
Using cordova-plugin-statusbar (2.1.1)
Using cordova-plugin-vibration (2.1.0)
Installing phonegap-ios-template 0.1.7 (was 0.1.4)
Generating Pods project
Integrating client project
Sending stats
Sending stats
Pod installation complete! There are 18 dependencies from the Podfile and 18 total pods installed.

```

Hope this helps and I look forward to chatting soon!
Holly

**Comment by stevengill** [comment]
You rock @hollyschinsky!!

**Comment by EddyVerbruggen** [comment]
W000t! Look at that [shiny new version](https://cocoapods.org/?q=cordova)! Thank you so much, it works perfectly for me :)

:heart_eyes:

**Comment by revolunet** [comment]
Thanks !
