### ISSUE TITLE
Packaging Cordova Webview project as a separate .framework

### ISSUE THREAD

**Issue by Ajaxy** [phonegap/phonegap-webview-ios#9]
Hello.

I want to make standalone `My.framework` for Swift projects, that only provides custom `MyViewController` (that internally extends `CDVViewController` and contains all needed HTML/JS content), that can be seamlessly used in any project (as kind of widget).

With help of [this tutorial](http://docs.phonegap.com/develop/1-embed-webview/ios/) I created Cocoa Touch Framework project instead of Single View Application and it seems to work well until the moment I try to insert it to another project — build fails with

> ld: framework not found Cordova for architecture x86_64

Seems that all cocoa pods frameworks (Cordova and all plugins) are not included in the bundle of the `My.framework` file. The point is that I don't want to package my framework as Cocoa Pod, I want that the using of it to be as simple as downloading and inserting `My.framework` file in any project.

What am I doing wrong? How to make `My.framework` include all needed dependencies? May be I need some special settings or some special build/bundle (Now  I'm trying to simply copy the file from `MyFramework/Products/My.framework`).

Thank you.

**Comment by revolunet** [comment]
Same goal here, any advancements ?

**Comment by Ajaxy** [comment]
I ended up using own CocoaPod instead of `.framework` file.

**Comment by revolunet** [comment]
so you mean same architecture as this project ?

**Comment by Ajaxy** [comment]
No, I created pod with this tutorial: https://guides.cocoapods.org/making/using-pod-lib-create
